### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by jbkunst** [metacran/PACKAGES#2]
Hi @gaborcsardi, 

Why this file stop to have updates? I know that exisit the crandb package, but to get all dependencies from all packages its a little slow than parse this file.

Regards,

**Comment by jbkunst** [comment]
Sorry for bother you, I just found http://crandb.r-pkg.org/-/all.

Thanks anyway for the package and the api.

**Comment by gaborcsardi** [comment]
Because I went abroad and someone turned off the machine under my desk..... sorry for the trouble, I'll try to fix it this week.

**Comment by jbkunst** [comment]
It's fine. I hope that "turned off" has not caused so many _big problems_. Regards,

**Comment by krlmlr** [comment]
No worries...

![Double facepalm](http://i.stack.imgur.com/jiFfM.jpg)
